apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-devfile-sample-go-basic-hdz2-sample
  namespace: bholifie-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:3724c73ca2a1efde0f01243cd0293e1581b0f38cdd257901b8dcb3f01daaaa2d
        name: container-image
        resources: {}
status: {}
