apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-devfile-sample-go-basic-hdz2-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-devfile-sample-go-basic-hdz2-sample
    app.kubernetes.io/part-of: test
  name: test-devfile-sample-go-basic-hdz2-sample
  namespace: bholifie-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-devfile-sample-go-basic-hdz2-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-devfile-sample-go-basic-hdz2-sample
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:3724c73ca2a1efde0f01243cd0293e1581b0f38cdd257901b8dcb3f01daaaa2d
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
