apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-devfile-sample-go-basic-hdz2-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-devfile-sample-go-basic-hdz2-sample
    app.kubernetes.io/part-of: test
  name: test-devfile-sample-go-basic-hdz2-sample
  namespace: bholifie-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-devfile-sample-go-basic-hdz2-sample
status:
  loadBalancer: {}
